### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by tsuyoponta** [tsuyoponta/furima-32375#9]
# フリマアプリのURL
https://furima-32375.herokuapp.com/
## Basic認証のIDとパスワード
**ID:** tsuyoponta
**パスワード:** 4127
## 出品者用のメールアドレスとパスワード
**メールアドレス:** sample@example.com
**パスワード:** 890iop
## 購入者用のメールアドレスとパスワード
**メールアドレス:** test@test.com
**パスワード:** 123qwe
## 購入用カードの番号・期限・セキュリティコード
**カードの番号:** 4242424242424242
**期限:** 3/2033
**セキュリティコード:** 123

**Comment by takumi0530** [comment]
@tsuyoponta さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/109758314-b875cd80-7c2e-11eb-87cd-e69b0a01fd0e.png)
